### PR TITLE
Add derives

### PR DESCRIPTION
**Pull request by LaurenzV**

### CODE REVIEW

**Comment by laurmaedje** [comment]
I think `Clone` makes sense, but does `Eq` and `PartialEq` really make sense for chunks?

As for `Debug`, we could have something like `Chunk(3)` when there are three objects in it.

**Comment by laurmaedje** [comment]
Or just `Chunk(..)` like for the `Pdf` struct.

**Comment by LaurenzV** [comment]
> I think Clone makes sense, but does Eq and PartialEq really make sense for chunks?

Damn, I already forgot why I needed it... Just tried it without it and still seems to compile fine for me. 😂 So I guess I'll remove it.

> As for Debug, we could have something like Chunk(3) when there are three objects in it.

Isn't `Debug` already implemented?

**Comment by laurmaedje** [comment]
> Isn't Debug already implemented?

Nevermind then, I only read the diff.

**Pull request merged**
