### PR TITLE
Change formatting of PostScriptOp

### PR DESCRIPTION
**Pull request by LaurenzV**
I hope that change is okay. It's very hard to deal with borrowed slices if your code building logic is based on recursion, which I believe shouldn't be uncommon (at least it's necessary in my case).

### CODE REVIEW

**Comment by LaurenzV** [comment]
and one more small change: having each operator on a new line looks very unreadable for long code, so I would suggest separating them by space instead.

**Comment by laurmaedje** [comment]
For what it's worth, you could probably keep the recursion and the borrowed data by using an arena data structure and it would be much more efficient. E.g. https://docs.rs/bumpalo/latest/bumpalo/. You would create a `Bump` at the top level and pass it down and have just one allocation instead of many.

**Comment by LaurenzV** [comment]
Will look into it, thanks!

**Comment by LaurenzV** [comment]
Seems to work great. 😄 So it's only the formatting thing I would like to change.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
